# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d8e0e5b2bdbcf10063e9cb1a71f95531d10b1ffce8b9148b7e7adb2467fd0c87c30e0320e4a9730b87f2e032f245c7850e0de499b529d378964b93bd176eb3d

test:
  secret_key_base: e55ca1c2ae6b27fa1027a62c4a6ac7ab37b3418fd6f8193ed10568d97c748024d62d97cf39ba0e1a7a0f7b0ffdfd962f1d4ee5a027b0e4fa9c512d743430a3e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
